[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
chain_ticket = "4uXFs66eEYQ8u51coqaypjF4wtRL4LQTML2kA5zMXUy4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./fixtures/metadata.so"
